language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get -qq -d update
  - sudo apt-get install xutils-dev

script:
  - cd fractint
  - makedepend -I headers common/*.c unix/*.c
  - make
