language: cpp

compiler:
  - gcc
  - clang

env:
  - ANALYZE=false
  - ANALYZE=true

before_install:
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq -d update

install:
  - sudo apt-get install xutils-dev libx11-dev cmake g++-4.8 clang cppcheck
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - g++ --version

script:
  - ./.travis.sh
