language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo apt-get -qq -d update

install:
  - sudo apt-get install xutils-dev libx11-dev cmake

script:
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" ..
  - make
