# Copyright (C) 2015, Richard Thomson
#

image: Visual Studio 2017

environment:
  GENERATOR: "Visual Studio 15 2017"

  matrix:
    - CONFIG: Debug

    - CONFIG: Release

build_script:
  - mkdir build
  - cd build
  - cmake -G "%GENERATOR%" ..
  - cmake --build . --config %CONFIG%
